projeto_mc426/auth/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('register/', views.registerPage, name='register'),
    path('login/', views.loginPage, name='login'),
    path('logout/', views.logoutPage, name='logout'),
]

projeto_mc426/feedback/urls.py
from django.urls import path
from . import views

app_name = 'feedback'
urlpatterns = [
    path('', views.index, name='feedback'),
    path('<int:feedback_id>/', views.detail, name='detail'),
    path('list/', views.list, name='list'),
    path('<int:feedback_id>/answer', views.answer, name='answer'),
]

projeto_mc426/projeto_mc426/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import render, redirect

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('auth.urls')),
    path('home/', include('home.urls')),
    path('', include('home.urls')),
    path('crime_register/', include('register.urls')),
]

projeto_mc426/feedback/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Feedback(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE
    )
    title = models.CharField("Título", max_length=80)
    description = models.TextField("Descrição")
    pub_date = models.DateTimeField("Data de publicação")
    answer = models.TextField("Resposta")
     
    @classmethod
    def create(cls, user, title, description, pub_date, answer):
        feedback = cls(user=user, title=title, description=description,
                   pub_date=pub_date, answer=answer)
        return feedback

projeto_mc426/feedback/forms.py
from django import forms

from .models import Feedback

class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback
        fields = ['title', 'description']

class FeedbackAnswerForm(forms.ModelForm):
    class Meta:
        model = Feedback
        fields = ['answer']

projeto_mc426/feedback/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.utils import timezone

from .forms import FeedbackForm, FeedbackAnswerForm
from .models import Feedback

# Create your views here.
@login_required
def index(request):
    if (request.method == 'POST'):
        feedback = Feedback(
            user = request.user,
            pub_date = timezone.now(),
            answer = "",
        )
        form = FeedbackForm(request.POST, instance=feedback)
        if form.is_valid():
           form.save()
           return render(request, "feedback/agradecimento.html")
    else:
        form = FeedbackForm()
    return render(request, "feedback/formulario.html", {'form': form})

@login_required
def detail(request, feedback_id):
    feedback = get_object_or_404(Feedback, pk=feedback_id)
    return render(request, "feedback/feedback.html", {'feedback': feedback})

@login_required
def list(request):
    list = Feedback.objects.order_by('-pub_date')
    return render(request, 'feedback/list.html', {'list': list})

@staff_member_required
def answer(request, feedback_id):
    feedback = Feedback.objects.get(pk=feedback_id)
    if (request.method == 'POST'):
        form = FeedbackAnswerForm(request.POST, instance=feedback)
        if form.is_valid():
            form.save()
            return render(request, "feedback/answer_sent.html", {'feedback': feedback})
    else:
        form = FeedbackAnswerForm()
    return render(request, "feedback/answer.html", {'feedback': feedback, 'form': form})

projeto_mc426/feedback/templates/feedback/agradecimento.html
{% extends "base.html" %}
{% block content %}
<h1> Envio de feedback </h1>
<p>Agradecemos a sua resposta</p>
{% endblock %}

projeto_mc426/feedback/templates/feedback/answer.html
{% extends "base.html" %}
{% block content %}
<head>
    <p><a href="{% url 'feedback:list'%}"> Voltar à lista de feedbacks</a></p>
</head>
<body>
    <h1>{{ feedback.title }}</h1>
    <p> Usuário: {{ feedback.user.username }}</p>
    <p> Enviado em {{ feedback.pub_date }}</p>
    <p> Descrição: {{ feedback.description }}</p>
    <form action="{% url 'feedback:answer' feedback.id%}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Enviar" />
      </form>
    
</body>

{% endblock %}

projeto_mc426/feedback/templates/feedback/answer_sent.html
{% extends "base.html" %}
{% block content %}
<p> Feedback respondido</p>
<p> <a href="{% url 'feedback:detail' feedback.id%}">Voltar ao feedback respondido</a></p>
{% endblock %}

projeto_mc426/feedback/templates/feedback/feedback.html
{% extends "base.html" %}
{% block content %}
<head>
    <p><a href="{% url 'feedback:list'%}"> Voltar à lista de feedbacks</a></p>
</head>
<body>
    <h1>{{ feedback.title }}</h1>
    <p> Usuário: {{ feedback.user.username }}</p>
    <p> Enviado em {{ feedback.pub_date }}</p>
    <p> Descrição: {{ feedback.description }}</p>
    {% if feedback.answer %}
        <p> Resposta: {{ feedback.answer }}</p>
    {% else %}
        {% if request.user.is_superuser %}
            <p><a href="{% url 'feedback:answer' feedback.id%}">Enviar resposta</a></p>
        {% endif %}
    {% endif %}
</body>
{% endblock %}

projeto_mc426/feedback/templates/feedback/formulario.html
{% extends "base.html" %}
{% block content %}
<h1> Envio de feedback </h1>
<p> Relate aqui a sua experiência com o site. </p>
<form action="{% url 'feedback:feedback' %}" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Enviar" />
</form>
<p> Voce pode ver feedbacks já enviados <a href="{% url 'feedback:list' %}">aqui</a>.</p>
{% endblock %}

projeto_mc426/feedback/templates/feedback/list.html
{% extends "base.html" %}
{% block content %}
<head>
    <h1> Lista de feedbacks enviados: </h1>
</head>
<body>
    <ul>
        {% if list %}
            {% for feedback in list %}
            <li><a = href="{% url 'feedback:detail' feedback.id %}">{{ feedback.title }}</a>, enviado em {{feedback.pub_date}} </li>
            {% endfor %}
        {% else %}
            <p> Não há nada aqui...</p>
        {% endif %}
    </ul>
</body>
{% endblock %}