projeto_mc426/auth/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('register/', views.registerPage, name='register'),
    path('login/', views.loginPage, name='login'),
    path('logout/', views.logoutPage, name='logout'),
]

projeto_mc426/projeto_mc426/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import render, redirect

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('auth.urls')),
    path('home/', include('home.urls')),
    path('', include('home.urls')),
    path('crime_register/', include('register.urls')),
]

projeto_mc426/register/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.crimeRegisterPage, name='crime_register'),
]

projeto_mc426/home/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class tipo_de_ocorrencia(models.Model):
    tdo_id = models.BigAutoField(primary_key=True)
    tdo_nome = models.CharField(max_length=255)
    tdo_peso = models.IntegerField()
    def __str__(self):
        return self.tdo_nome

class registro_de_ocorrencia(models.Model):
    rdo_id = models.BigAutoField(primary_key=True)
    rdo_tdo = models.ForeignKey(
        tipo_de_ocorrencia, on_delete=models.CASCADE, verbose_name="Tipo de Ocorrência"
    )
    rdo_cep = models.CharField("CEP", max_length=50)
    rdo_rua = models.CharField("Rua", max_length=100)
    rdo_bairro = models.CharField("Bairro", max_length=50)
    rdo_cidade = models.CharField("Cidade", max_length=50)
    rdo_estado = models.CharField("Estado", max_length=50)
    rdo_numero = models.IntegerField("Número")
    rdo_lat = models.DecimalField("Latitude", max_digits=10, decimal_places=6)
    rdo_lng = models.DecimalField("Longitute", max_digits=10, decimal_places=6)
    rdo_dtocorrencia = models.DateField("Data da Ocorrência")
    rdo_hrocorrencia = models.TimeField("Hora da Ocorrência")

projeto_mc426/register/models.py
from django.db import models

# Create your models here.

projeto_mc426/register/forms.py
from django import forms

from home.models import *

class registro_de_ocorrenciaForm(forms.ModelForm):
    class Meta:
        model = registro_de_ocorrencia
        fields = ['rdo_tdo', 'rdo_cep','rdo_rua','rdo_bairro',
                  'rdo_cidade','rdo_estado','rdo_numero',]
        

projeto_mc426/register/views.py
from django.contrib import messages
from django.shortcuts import redirect, render
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from register.forms import registro_de_ocorrenciaForm
from decimal import Decimal
from home.models import *
import requests
# Create your views here.

def getLocationData(rua, bairro, cidade, estado, numero):
    query = f'{rua}+{bairro}+{cidade}+{estado}+{numero}'
    params = {'format': 'json', 'q': query}
    response = requests.get('https://nominatim.openstreetmap.org/search', params=params)
    if response.status_code == 200:
        data = response.json()
        if data:
            return data[0].get('lat'), data[0].get('lon')
    return None, None

@login_required
def crimeRegisterPage(request):
    if request.method == 'POST':
        form = registro_de_ocorrenciaForm(request.POST)

        if form.is_valid():
            registro_de_ocorrencia()
            cleaned_data = form.cleaned_data
            lat, lng = getLocationData(
                cleaned_data.get("rdo_rua"), 
                cleaned_data.get("rdo_bairro"),
                cleaned_data.get("rdo_cidade"), 
                cleaned_data.get("rdo_estado"),
                cleaned_data.get("rdo_numero")
            )

            if lat is not None and lng is not None:
                registro = form.save(commit=False)
                registro.rdo_lat = lat
                registro.rdo_lng = lng
                registro.rdo_dtocorrencia = timezone.now().date()
                registro.rdo_hrocorrencia = timezone.now().time()
                registro.save()
                return render(request, 'crime_register_agradecimento.html')
            else:
                form.add_error(None, 'Local não encontrado.')
                return render(request, 'crime_register_erro.html', {'form': form})
        return render(request, 'crime_register.html', {'form': form})
    else:
        form = registro_de_ocorrenciaForm()
    return render(request, 'crime_register.html', {'form': form})
    

projeto_mc426/register/templates/crime_register.html
<!DOCTYPE html>
<html lang="pt-br">
{% extends "base.html" %}
{% block content %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Inclusão do jQuery -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    
    <!-- Inclusão do jQuery Mask Plugin -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.min.js"></script>
    <title>Registro de Ocorrência</title>
</head>

<body>

    <h2>Registro de Ocorrência</h2>
	<p>Preencha os seguintes campos para registrar a sua ocorrência.</p>
    <form action="{% url 'crime_register' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <!--<input type="button" value="Voltar" href="{% url "home" %}"> -->
        <input type="submit" value="Enviar" />
      </form>      
    <script>
        $('#id_rdo_cep').parent().append('<span id="loading" style="display: none;">Buscando...</span>');

        $(document).ready(function(){
            $('#id_rdo_cep').mask('00000-000'); //aplica mascara de CPF no campo
  
            $('#id_rdo_cep').mask('00000-000').on('blur', function(){ //faz a busca por CPF e preenche os campos
                var cep = $(this).val().replace(/\D/g, '');
                if (cep.length === 8) {

                    $('#loading').show();
                    $.ajax({
                        url: 'https://viacep.com.br/ws/' + cep + '/json/',
                        method: 'GET',
                        dataType: 'json',
                        success: function(data){
                            if (!("erro" in data)) {
                                $('#id_rdo_rua').val(data.logradouro).prop( "readonly", true );
                                $('#id_rdo_bairro').val(data.bairro).prop( "readonly", true );
                                $('#id_rdo_cidade').val(data.localidade).prop( "readonly", true );
                                $('#id_rdo_estado').val(data.uf).prop( "readonly", true );
                                $('#loading').hide();
                            } else {
                                // CEP não encontrado ou erro na requisição
                                $('#id_rdo_rua').val("").prop( "readonly", false );
                                $('#id_rdo_bairro').val("").prop( "readonly", false );
                                $('#id_rdo_cidade').val("").prop( "readonly", false );
                                $('#id_rdo_estado').val("").prop( "readonly", false );
                                $('#loading').hide();
                            }
                        }
                    });
                }
            });
        });
    </script>
</body>
{% endblock %}
</html>

projeto_mc426/register/templates/crime_register_agradecimento.html
<!DOCTYPE html>
{% extends "base.html" %}
{% block content %}

<h2>Agradecemos o seu registro.</h2>
<br><br>
<h3>Sua ocorrência aparecerá no mapa o mais brevemente possível.</h3>
<br><br>
<h3>Quaisquer novas ocorrências, não hesite em falar conosco.</h3>

{% endblock %}

projeto_mc426/register/templates/crime_register_erro.html
<!DOCTYPE html>

<h2>Erro ao salvar.</h2>
{% if form.non_field_errors%} 
    <div class="alert alert-danger">
        {% for error in form.non_field_errors %}
            <p>{{ error }}</p>
        {% endfor %}
    </div>
{% endif %}
<a href="{% url 'crime_register' %}"><button>Voltar para o registro</button></a>